"""initial schema with events and aggregations

Revision ID: 64660327c5d2
Revises: 
Create Date: 2026-02-28 18:40:58.428400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64660327c5d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_2026_04',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'timestamp', name=op.f('events_2026_04_pkey'))
    )
    op.create_index(op.f('events_2026_04_user_id_timestamp_idx'), 'events_2026_04', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_04_user_id_idx'), 'events_2026_04', ['user_id'], unique=False)
    op.create_index(op.f('events_2026_04_timestamp_idx'), 'events_2026_04', ['timestamp'], unique=False)
    op.create_index(op.f('events_2026_04_session_id_idx'), 'events_2026_04', ['session_id'], unique=False)
    op.create_index(op.f('events_2026_04_properties_idx'), 'events_2026_04', ['properties'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_04_metadata_idx'), 'events_2026_04', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_04_event_type_timestamp_idx'), 'events_2026_04', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_04_event_type_idx'), 'events_2026_04', ['event_type'], unique=False)
    op.create_table('events_2026_02',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'timestamp', name=op.f('events_2026_02_pkey'))
    )
    op.create_index(op.f('events_2026_02_user_id_timestamp_idx'), 'events_2026_02', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_02_user_id_idx'), 'events_2026_02', ['user_id'], unique=False)
    op.create_index(op.f('events_2026_02_timestamp_idx'), 'events_2026_02', ['timestamp'], unique=False)
    op.create_index(op.f('events_2026_02_session_id_idx'), 'events_2026_02', ['session_id'], unique=False)
    op.create_index(op.f('events_2026_02_properties_idx'), 'events_2026_02', ['properties'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_02_metadata_idx'), 'events_2026_02', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_02_event_type_timestamp_idx'), 'events_2026_02', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_02_event_type_idx'), 'events_2026_02', ['event_type'], unique=False)
    op.create_table('events_2026_03',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'timestamp', name=op.f('events_2026_03_pkey'))
    )
    op.create_index(op.f('events_2026_03_user_id_timestamp_idx'), 'events_2026_03', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_03_user_id_idx'), 'events_2026_03', ['user_id'], unique=False)
    op.create_index(op.f('events_2026_03_timestamp_idx'), 'events_2026_03', ['timestamp'], unique=False)
    op.create_index(op.f('events_2026_03_session_id_idx'), 'events_2026_03', ['session_id'], unique=False)
    op.create_index(op.f('events_2026_03_properties_idx'), 'events_2026_03', ['properties'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_03_metadata_idx'), 'events_2026_03', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_03_event_type_timestamp_idx'), 'events_2026_03', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_03_event_type_idx'), 'events_2026_03', ['event_type'], unique=False)
    op.create_table('events_2026_01',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'timestamp', name=op.f('events_2026_01_pkey'))
    )
    op.create_index(op.f('events_2026_01_user_id_timestamp_idx'), 'events_2026_01', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_01_user_id_idx'), 'events_2026_01', ['user_id'], unique=False)
    op.create_index(op.f('events_2026_01_timestamp_idx'), 'events_2026_01', ['timestamp'], unique=False)
    op.create_index(op.f('events_2026_01_session_id_idx'), 'events_2026_01', ['session_id'], unique=False)
    op.create_index(op.f('events_2026_01_properties_idx'), 'events_2026_01', ['properties'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_01_metadata_idx'), 'events_2026_01', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_01_event_type_timestamp_idx'), 'events_2026_01', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_01_event_type_idx'), 'events_2026_01', ['event_type'], unique=False)
    op.create_table('events_2026_05',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'timestamp', name=op.f('events_2026_05_pkey'))
    )
    op.create_index(op.f('events_2026_05_user_id_timestamp_idx'), 'events_2026_05', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_05_user_id_idx'), 'events_2026_05', ['user_id'], unique=False)
    op.create_index(op.f('events_2026_05_timestamp_idx'), 'events_2026_05', ['timestamp'], unique=False)
    op.create_index(op.f('events_2026_05_session_id_idx'), 'events_2026_05', ['session_id'], unique=False)
    op.create_index(op.f('events_2026_05_properties_idx'), 'events_2026_05', ['properties'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_05_metadata_idx'), 'events_2026_05', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('events_2026_05_event_type_timestamp_idx'), 'events_2026_05', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('events_2026_05_event_type_idx'), 'events_2026_05', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('events_2026_05_event_type_idx'), table_name='events_2026_05')
    op.drop_index(op.f('events_2026_05_event_type_timestamp_idx'), table_name='events_2026_05')
    op.drop_index(op.f('events_2026_05_metadata_idx'), table_name='events_2026_05', postgresql_using='gin')
    op.drop_index(op.f('events_2026_05_properties_idx'), table_name='events_2026_05', postgresql_using='gin')
    op.drop_index(op.f('events_2026_05_session_id_idx'), table_name='events_2026_05')
    op.drop_index(op.f('events_2026_05_timestamp_idx'), table_name='events_2026_05')
    op.drop_index(op.f('events_2026_05_user_id_idx'), table_name='events_2026_05')
    op.drop_index(op.f('events_2026_05_user_id_timestamp_idx'), table_name='events_2026_05')
    op.drop_table('events_2026_05')
    op.drop_index(op.f('events_2026_01_event_type_idx'), table_name='events_2026_01')
    op.drop_index(op.f('events_2026_01_event_type_timestamp_idx'), table_name='events_2026_01')
    op.drop_index(op.f('events_2026_01_metadata_idx'), table_name='events_2026_01', postgresql_using='gin')
    op.drop_index(op.f('events_2026_01_properties_idx'), table_name='events_2026_01', postgresql_using='gin')
    op.drop_index(op.f('events_2026_01_session_id_idx'), table_name='events_2026_01')
    op.drop_index(op.f('events_2026_01_timestamp_idx'), table_name='events_2026_01')
    op.drop_index(op.f('events_2026_01_user_id_idx'), table_name='events_2026_01')
    op.drop_index(op.f('events_2026_01_user_id_timestamp_idx'), table_name='events_2026_01')
    op.drop_table('events_2026_01')
    op.drop_index(op.f('events_2026_03_event_type_idx'), table_name='events_2026_03')
    op.drop_index(op.f('events_2026_03_event_type_timestamp_idx'), table_name='events_2026_03')
    op.drop_index(op.f('events_2026_03_metadata_idx'), table_name='events_2026_03', postgresql_using='gin')
    op.drop_index(op.f('events_2026_03_properties_idx'), table_name='events_2026_03', postgresql_using='gin')
    op.drop_index(op.f('events_2026_03_session_id_idx'), table_name='events_2026_03')
    op.drop_index(op.f('events_2026_03_timestamp_idx'), table_name='events_2026_03')
    op.drop_index(op.f('events_2026_03_user_id_idx'), table_name='events_2026_03')
    op.drop_index(op.f('events_2026_03_user_id_timestamp_idx'), table_name='events_2026_03')
    op.drop_table('events_2026_03')
    op.drop_index(op.f('events_2026_02_event_type_idx'), table_name='events_2026_02')
    op.drop_index(op.f('events_2026_02_event_type_timestamp_idx'), table_name='events_2026_02')
    op.drop_index(op.f('events_2026_02_metadata_idx'), table_name='events_2026_02', postgresql_using='gin')
    op.drop_index(op.f('events_2026_02_properties_idx'), table_name='events_2026_02', postgresql_using='gin')
    op.drop_index(op.f('events_2026_02_session_id_idx'), table_name='events_2026_02')
    op.drop_index(op.f('events_2026_02_timestamp_idx'), table_name='events_2026_02')
    op.drop_index(op.f('events_2026_02_user_id_idx'), table_name='events_2026_02')
    op.drop_index(op.f('events_2026_02_user_id_timestamp_idx'), table_name='events_2026_02')
    op.drop_table('events_2026_02')
    op.drop_index(op.f('events_2026_04_event_type_idx'), table_name='events_2026_04')
    op.drop_index(op.f('events_2026_04_event_type_timestamp_idx'), table_name='events_2026_04')
    op.drop_index(op.f('events_2026_04_metadata_idx'), table_name='events_2026_04', postgresql_using='gin')
    op.drop_index(op.f('events_2026_04_properties_idx'), table_name='events_2026_04', postgresql_using='gin')
    op.drop_index(op.f('events_2026_04_session_id_idx'), table_name='events_2026_04')
    op.drop_index(op.f('events_2026_04_timestamp_idx'), table_name='events_2026_04')
    op.drop_index(op.f('events_2026_04_user_id_idx'), table_name='events_2026_04')
    op.drop_index(op.f('events_2026_04_user_id_timestamp_idx'), table_name='events_2026_04')
    op.drop_table('events_2026_04')
    # ### end Alembic commands ###
